### ISSUE TITLE
能不能加个中文错误提示?

### ISSUE THREAD

**Issue by qdsang** [fouber/fis-lint-jshint#1]
http://ued.ctrip.com/blog/?p=2733

**Comment by fouber** [comment]
@qdsang 

已发布新版本，支持中文报错，参考新的README， `i18n` 参数。

**Comment by qdsang** [comment]
@fouber  太帅了. 3Q
尝试非常好

---

嗷感觉这实现方式不太好, 只能匹配上少部分

**Comment by fouber** [comment]
@qdsang 聊胜于无，哈哈
